//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duracellko.PlanningPoker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duracellko.PlanningPoker.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer &quot;{observer}&quot; in Scrum team &quot;{scrumTeam}&quot; received message: {hasMessages}.
        /// </summary>
        internal static string Debug_ObserverMessageReceived {
            get {
                return ResourceManager.GetString("Debug_ObserverMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum team &quot;{scrumTeam}&quot; was locked..
        /// </summary>
        internal static string Debug_ReadScrumTeam {
            get {
                return ResourceManager.GetString("Debug_ReadScrumTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum team &quot;{scrumTeam}&quot; was added..
        /// </summary>
        internal static string Debug_ScrumTeamAdded {
            get {
                return ResourceManager.GetString("Debug_ScrumTeamAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum team &quot;{scrumTeam}&quot; was removed..
        /// </summary>
        internal static string Debug_ScrumTeamRemoved {
            get {
                return ResourceManager.GetString("Debug_ScrumTeamRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAsyncResult object was not provided by BeginGetMessage method..
        /// </summary>
        internal static string Error_EndGetMessagesAsyncResult {
            get {
                return ResourceManager.GetString("Error_EndGetMessagesAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid session ID..
        /// </summary>
        internal static string Error_InvalidSessionId {
            get {
                return ResourceManager.GetString("Error_InvalidSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member name cannot be longer than 50 characters..
        /// </summary>
        internal static string Error_MemberNameTooLong {
            get {
                return ResourceManager.GetString("Error_MemberNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team member &quot;{0}&quot; has not been found..
        /// </summary>
        internal static string Error_MemberNotFound {
            get {
                return ResourceManager.GetString("Error_MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create Scrum Team &quot;{0}&quot;. Team with that name already exists..
        /// </summary>
        internal static string Error_ScrumTeamAlreadyExists {
            get {
                return ResourceManager.GetString("Error_ScrumTeamAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum Team &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string Error_ScrumTeamNotExist {
            get {
                return ResourceManager.GetString("Error_ScrumTeamNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum Team cannot be opened..
        /// </summary>
        internal static string Error_ScrumTeamTimeout {
            get {
                return ResourceManager.GetString("Error_ScrumTeamTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name cannot be longer than 50 characters..
        /// </summary>
        internal static string Error_TeamNameTooLong {
            get {
                return ResourceManager.GetString("Error_TeamNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting inactive observers in Scrum team: {scrumTeam}.
        /// </summary>
        internal static string Info_DisconnectingInactiveObservers {
            get {
                return ResourceManager.GetString("Info_DisconnectingInactiveObservers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum team member message (team: {scrumTeam}, ID: {messageId}, type: {messageType}, member: {observer}).
        /// </summary>
        internal static string Info_MemberMessage {
            get {
                return ResourceManager.GetString("Info_MemberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum team &quot;{scrumTeam}&quot; was attached..
        /// </summary>
        internal static string Info_ScrumTeamAttached {
            get {
                return ResourceManager.GetString("Info_ScrumTeamAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum team &quot;{scrumTeam}&quot; was created with Scrum master: {scrumMaster}.
        /// </summary>
        internal static string Info_ScrumTeamCreated {
            get {
                return ResourceManager.GetString("Info_ScrumTeamCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum team message (team: {scrumTeam}, ID: {messageId}, type: {messageType}).
        /// </summary>
        internal static string Info_ScrumTeamMessage {
            get {
                return ResourceManager.GetString("Info_ScrumTeamMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum team &quot;{scrumTeam}&quot; was removed..
        /// </summary>
        internal static string Info_ScrumTeamRemoved {
            get {
                return ResourceManager.GetString("Info_ScrumTeamRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting all Scrum teams..
        /// </summary>
        internal static string Repository_Debug_DeleteAllScrumTeams {
            get {
                return ResourceManager.GetString("Repository_Debug_DeleteAllScrumTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting expired Scrum teams..
        /// </summary>
        internal static string Repository_Debug_DeleteExpiredScrumTeams {
            get {
                return ResourceManager.GetString("Repository_Debug_DeleteExpiredScrumTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Scrum team: {scrumTeam}.
        /// </summary>
        internal static string Repository_Debug_DeleteScrumTeam {
            get {
                return ResourceManager.GetString("Repository_Debug_DeleteScrumTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Scrum team: {scrumTeam}.
        /// </summary>
        internal static string Repository_Debug_LoadScrumTeam {
            get {
                return ResourceManager.GetString("Repository_Debug_LoadScrumTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Scrum team names..
        /// </summary>
        internal static string Repository_Debug_LoadScrumTeamNames {
            get {
                return ResourceManager.GetString("Repository_Debug_LoadScrumTeamNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Scrum team: {scrumTeam}.
        /// </summary>
        internal static string Repository_Debug_SaveScrumTeam {
            get {
                return ResourceManager.GetString("Repository_Debug_SaveScrumTeam", resourceCulture);
            }
        }
    }
}
