//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duracellko.PlanningPoker.Azure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duracellko.PlanningPoker.Azure.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Bus subscription &quot;{subscriptionId}&quot; was deleted due to inactivity by Node ID &quot;{nodeId}&quot;..
        /// </summary>
        internal static string AzureServiceBus_Debug_InactiveSubscriptionDeleted {
            get {
                return ResourceManager.GetString("AzureServiceBus_Debug_InactiveSubscriptionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Bus message was received (Topic: {topic}, NodeID: {nodeId}, MessageID: {messageId}).
        /// </summary>
        internal static string AzureServiceBus_Debug_MessageReceived {
            get {
                return ResourceManager.GetString("AzureServiceBus_Debug_MessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent to Azure Service Bus..
        /// </summary>
        internal static string AzureServiceBus_Debug_SendMessage {
            get {
                return ResourceManager.GetString("AzureServiceBus_Debug_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Bus subscription is alive (Topic: {topic}, NodeID: {nodeId}, SubscriptionID: {subscriptionId}).
        /// </summary>
        internal static string AzureServiceBus_Debug_SubscriptionAliveMessageReceived {
            get {
                return ResourceManager.GetString("AzureServiceBus_Debug_SubscriptionAliveMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification sent, that Node ID &quot;{nodeId}&quot; is alive..
        /// </summary>
        internal static string AzureServiceBus_Debug_SubscriptionAliveSent {
            get {
                return ResourceManager.GetString("AzureServiceBus_Debug_SubscriptionAliveSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Bus subscription was created (Topic: {topic}, NodeID: {nodeId}).
        /// </summary>
        internal static string AzureServiceBus_Debug_SubscriptionCreated {
            get {
                return ResourceManager.GetString("AzureServiceBus_Debug_SubscriptionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Bus subscription was deleted (Topic: {topic}, NodeID: {nodeId}).
        /// </summary>
        internal static string AzureServiceBus_Debug_SubscriptionDeleted {
            get {
                return ResourceManager.GetString("AzureServiceBus_Debug_SubscriptionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Bus message processing failed (Topic: {topic}, NodeID: {nodeId}, MessageID: {messageId}).
        /// </summary>
        internal static string AzureServiceBus_Error_MessageError {
            get {
                return ResourceManager.GetString("AzureServiceBus_Error_MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending message to Azure Service Bus..
        /// </summary>
        internal static string AzureServiceBus_Error_SendMessage {
            get {
                return ResourceManager.GetString("AzureServiceBus_Error_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Bus subscriptions maintenance failed for Node ID: {nodeId}.
        /// </summary>
        internal static string AzureServiceBus_Error_SubscriptionsMaintenance {
            get {
                return ResourceManager.GetString("AzureServiceBus_Error_SubscriptionsMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Bus message was processed (Topic: {topic}, NodeID: {nodeId}, MessageID: {messageId}).
        /// </summary>
        internal static string AzureServiceBus_Info_MessageProcessed {
            get {
                return ResourceManager.GetString("AzureServiceBus_Info_MessageProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create Scrum Team &quot;{0}&quot;. Team with that name already exists..
        /// </summary>
        internal static string Error_ScrumTeamAlreadyExists {
            get {
                return ResourceManager.GetString("Error_ScrumTeamAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning Poker Azure Node message received (NodeID: {nodeId}, Sender: {sender}, Recipient: {recipient}, Type: {type}).
        /// </summary>
        internal static string Info_NodeMessageReceived {
            get {
                return ResourceManager.GetString("Info_NodeMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning Poker Azure Node message sent (NodeID: {nodeId}, Sender: {sender}, Recipient: {recipient}, Type: {type}).
        /// </summary>
        internal static string Info_NodeMessageSent {
            get {
                return ResourceManager.GetString("Info_NodeMessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning Poker Azure Node &quot;{nodeId}&quot; is initialized..
        /// </summary>
        internal static string Info_PlanningPokerAzureNodeInitialized {
            get {
                return ResourceManager.GetString("Info_PlanningPokerAzureNodeInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning Poker Azure Node &quot;{nodeId}&quot; is starting..
        /// </summary>
        internal static string Info_PlanningPokerAzureNodeStarting {
            get {
                return ResourceManager.GetString("Info_PlanningPokerAzureNodeStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning Poker Azure Node &quot;{nodeId}&quot; is stopping..
        /// </summary>
        internal static string Info_PlanningPokerAzureNodeStopping {
            get {
                return ResourceManager.GetString("Info_PlanningPokerAzureNodeStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning Poker Azure Node message received (NodeID: {nodeId}, Sender: {sender}, Recipient: {recipient}, Type: {type}, Scrum Team: {scrumTeam}).
        /// </summary>
        internal static string Info_ScrumTeamCreatedNodeMessageReceived {
            get {
                return ResourceManager.GetString("Info_ScrumTeamCreatedNodeMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning Poker Azure Node message received (NodeID: {nodeId}, Sender: {sender}, Recipient: {recipient}, Type: {type}, Scrum Team: {scrumTeam}, Message type: {messageType}).
        /// </summary>
        internal static string Info_ScrumTeamNodeMessageReceived {
            get {
                return ResourceManager.GetString("Info_ScrumTeamNodeMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry to request Scrum team list for Node &quot;{nodeId}&quot;..
        /// </summary>
        internal static string Warning_RetryRequestTeamList {
            get {
                return ResourceManager.GetString("Warning_RetryRequestTeamList", resourceCulture);
            }
        }
    }
}
