//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duracellko.PlanningPoker.Domain {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duracellko.PlanningPoker.Domain.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A desserialização do Time Scrum falhou..
        /// </summary>
        internal static string Error_DeserializationFailed {
            get {
                return ResourceManager.GetString("Error_DeserializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível iniciar a estimativa. A estimativa já está em andamento..
        /// </summary>
        internal static string Error_EstimationIsInProgress {
            get {
                return ResourceManager.GetString("Error_EstimationIsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A estimativa do valor {0} não está disponível na equipe..
        /// </summary>
        internal static string Error_EstimationIsNotAvailableInTeam {
            get {
                return ResourceManager.GetString("Error_EstimationIsNotAvailableInTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O resultado da estimativa é somente leitura..
        /// </summary>
        internal static string Error_EstimationResultIsReadOnly {
            get {
                return ResourceManager.GetString("Error_EstimationResultIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID de sessão inválido..
        /// </summary>
        internal static string Error_InvalidSessionId {
            get {
                return ResourceManager.GetString("Error_InvalidSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A duração do temporizador deve ser superior a 0 segundos..
        /// </summary>
        internal static string Error_InvalidTimerDuraction {
            get {
                return ResourceManager.GetString("Error_InvalidTimerDuraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O membro ou observador chamado &apos;{0}&apos; já existe na equipe..
        /// </summary>
        internal static string Error_MemberAlreadyExists {
            get {
                return ResourceManager.GetString("Error_MemberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O membro dado não estava presente no resultado da estimativa..
        /// </summary>
        internal static string Error_MemberNotInResult {
            get {
                return ResourceManager.GetString("Error_MemberNotInResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Scrum Master já está definido para a equipe..
        /// </summary>
        internal static string Error_ScrumMasterAlreadyExists {
            get {
                return ResourceManager.GetString("Error_ScrumMasterAlreadyExists", resourceCulture);
            }
        }
    }
}
