//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duracellko.PlanningPoker.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duracellko.PlanningPoker.Client.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMessages is already in progress..
        /// </summary>
        internal static string Error_GetMessagesInProgress {
            get {
                return ResourceManager.GetString("Error_GetMessagesInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrumMaster cannot disconnect himself..
        /// </summary>
        internal static string Error_ScrumMasterSelfDisconnect {
            get {
                return ResourceManager.GetString("Error_ScrumMasterSelfDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer duration must be greater than 0 seconds..
        /// </summary>
        internal static string Error_TimerDurationZeroOrNegative {
            get {
                return ResourceManager.GetString("Error_TimerDurationZeroOrNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer cannot be started without configured dispatcher..
        /// </summary>
        internal static string Error_TimerStartedWithoutDispatcher {
            get {
                return ResourceManager.GetString("Error_TimerStartedWithoutDispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ½.
        /// </summary>
        internal static string Estimation_Half {
            get {
                return ResourceManager.GetString("Estimation_Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∞.
        /// </summary>
        internal static string Estimation_Infinity {
            get {
                return ResourceManager.GetString("Estimation_Infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string Estimation_L {
            get {
                return ResourceManager.GetString("Estimation_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🦎.
        /// </summary>
        internal static string Estimation_Lizard {
            get {
                return ResourceManager.GetString("Estimation_Lizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string Estimation_M {
            get {
                return ResourceManager.GetString("Estimation_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📜.
        /// </summary>
        internal static string Estimation_Paper {
            get {
                return ResourceManager.GetString("Estimation_Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string Estimation_QuestionMark {
            get {
                return ResourceManager.GetString("Estimation_QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💎.
        /// </summary>
        internal static string Estimation_Rock {
            get {
                return ResourceManager.GetString("Estimation_Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Estimation_S {
            get {
                return ResourceManager.GetString("Estimation_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✂.
        /// </summary>
        internal static string Estimation_Scissors {
            get {
                return ResourceManager.GetString("Estimation_Scissors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🖖.
        /// </summary>
        internal static string Estimation_Spock {
            get {
                return ResourceManager.GetString("Estimation_Spock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XL.
        /// </summary>
        internal static string Estimation_XL {
            get {
                return ResourceManager.GetString("Estimation_XL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XS.
        /// </summary>
        internal static string Estimation_XS {
            get {
                return ResourceManager.GetString("Estimation_XS", resourceCulture);
            }
        }
    }
}
