# Build ASP.NET Core project using Azure Pipelines

parameters:
  RunEnd2EndTests: true
  PublishArtifacts: true

jobs:
- job: PlanningPokerApp
  displayName: PlanningPoker App

  pool:
    vmImage: ubuntu-latest

  workspace:
    clean: all

  variables:
    RunEnd2EndTests: ${{ parameters.RunEnd2EndTests }}
    PublishArtifacts: ${{ parameters.PublishArtifacts }}

  steps:
  - task: UseDotNet@2
    displayName: Install .NET SDK
    inputs:
      version: 7.0.x

  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: 18.x

  - pwsh: './scripts/UpdateVersion.ps1 -VersionNumber $env:BUILD_BUILDID'
    displayName: 'PowerShell UpdateVersion.ps1'
    failOnStderr: true

  - task: Npm@1
    displayName: npm install
    inputs:
      command: install
    condition: and(succeeded(), eq(variables['RunEnd2EndTests'], 'true'))

  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: $(BuildProjects)
      arguments: --verbosity normal

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      projects: $(BuildProjects)
      arguments: --configuration $(BuildConfiguration) --verbosity normal

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: '$(Build.SourcesDirectory)/Build/bin/$(BuildConfiguration)/net7.0/*.Test.dll'
      testRunTitle: Planning Poker

  - pwsh: .\node_modules\.bin\selenium-standalone install
    displayName: Install Selenium
    workingDirectory: $(Build.SourcesDirectory)
    condition: and(succeeded(), eq(variables['RunEnd2EndTests'], 'true'))

  - task: DotNetCoreCLI@2
    displayName: dotnet test Duracellko.PlanningPoker.E2ETest
    inputs:
      command: test
      projects: '$(Build.SourcesDirectory)/Build/bin/$(BuildConfiguration)/net7.0/Duracellko.PlanningPoker.E2ETest.dll'
      testRunTitle: Planning Poker E2E
    condition: and(succeeded(), eq(variables['RunEnd2EndTests'], 'true'))

  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: $(PublishProjects)
      arguments: --configuration $(BuildConfiguration) --verbosity normal
      zipAfterPublish: false
    condition: and(succeeded(), eq(variables['PublishArtifacts'], 'true'))

  - task: ArchiveFiles@2
    displayName: Zip web
    inputs:
      archiveType: zip
      archiveFile: $(Build.StagingDirectory)/web/web.zip
      rootFolderOrFile: $(Build.SourcesDirectory)/Build/web/$(BuildConfiguration)/net7.0/publish
      includeRootFolder: false
      replaceExistingArchive: true
    condition: and(succeeded(), eq(variables['PublishArtifacts'], 'true'))

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: web'
    inputs:
      PathtoPublish: $(Build.StagingDirectory)/web
      ArtifactName: web
    condition: and(succeeded(), eq(variables['PublishArtifacts'], 'true'))

  - task: CopyFiles@2
    displayName: Copy screenshots
    inputs:
      SourceFolder: $(Build.SourcesDirectory)/Build/bin/$(BuildConfiguration)/net7.0/Screenshots
      TargetFolder: $(Build.Build.StagingDirectory)/screenshots
      CleanTargetFolder: true
    condition: and(succeeded(), eq(variables['RunEnd2EndTests'], 'true'))

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: screenshots'
    inputs:
      PathtoPublish: $(Build.Build.StagingDirectory)/screenshots
      ArtifactName: screenshots
    condition: and(succeeded(), eq(variables['RunEnd2EndTests'], 'true'))
