# Build ASP.NET Core project using Azure Pipelines

parameters:
  RunEnd2EndTests: true
  RunContainerTests: true
  PublishArtifacts: true

jobs:
- job: PlanningPokerApp
  displayName: PlanningPoker App

  pool:
    vmImage: ubuntu-latest

  workspace:
    clean: all

  variables:
    RunEnd2EndTests: ${{ parameters.RunEnd2EndTests }}
    RunContainerTests: ${{ parameters.RunContainerTests }}
    PublishArtifacts: ${{ parameters.PublishArtifacts }}

  steps:
  - task: UseDotNet@2
    displayName: Install .NET SDK
    inputs:
      version: 9.0.x

  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: $(BuildProjects)
      arguments: --verbosity normal

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      projects: $(BuildProjects)
      arguments: --configuration $(BuildConfiguration) -p:VersionBuild=$(Build.BuildId) --no-restore --verbosity normal

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: $(UnitTestProjects)
      arguments: --configuration $(BuildConfiguration) -p:VersionBuild=$(Build.BuildId) --no-build
      testRunTitle: Planning Poker

  - pwsh: '.\artifacts\bin\Duracellko.PlanningPoker.E2ETest\$(BuildConfiguration)\playwright.ps1 install chromium'
    displayName: Install Playwright
    workingDirectory: $(Build.SourcesDirectory)
    condition: and(succeeded(), eq(variables['RunEnd2EndTests'], 'true'))

  - task: DotNetCoreCLI@2
    displayName: dotnet test Duracellko.PlanningPoker.E2ETest
    inputs:
      command: test
      projects: '$(Build.SourcesDirectory)/artifacts/bin/Duracellko.PlanningPoker.E2ETest/$(BuildConfiguration)/Duracellko.PlanningPoker.E2ETest.dll'
      testRunTitle: Planning Poker E2E
    condition: and(succeeded(), eq(variables['RunEnd2EndTests'], 'true'))

  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: $(PublishProjects)
      arguments: --configuration $(BuildConfiguration) -p:VersionBuild=$(Build.BuildId) --verbosity normal
      zipAfterPublish: false

  - task: ArchiveFiles@2
    displayName: Zip web
    inputs:
      archiveType: zip
      archiveFile: $(Build.StagingDirectory)/web/web.zip
      rootFolderOrFile: $(Build.SourcesDirectory)/artifacts/publish/Duracellko.PlanningPoker.Web/$(BuildConfiguration)
      includeRootFolder: false
      replaceExistingArchive: true
    condition: and(succeeded(), eq(variables['PublishArtifacts'], 'true'))

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: web'
    inputs:
      PathtoPublish: $(Build.StagingDirectory)/web
      ArtifactName: web
    condition: and(succeeded(), eq(variables['PublishArtifacts'], 'true'))

  - task: DotNetCoreCLI@2
    displayName: dotnet publish container
    inputs:
      command: publish
      publishWebProjects: false
      projects: $(PublishProjects)
      arguments: /t:PublishContainer --configuration $(BuildConfiguration) -p:VersionBuild=$(Build.BuildId) -p:ContainerArchiveOutputPath=../../artifacts/staging/planningpoker4azure.tar.gz --verbosity normal
      zipAfterPublish: false
    condition: and(succeeded(), or(eq(variables['PublishArtifacts'], 'true'), eq(variables['RunContainerTests'], 'true')))

  - pwsh: '& docker image load -i artifacts/staging/planningpoker4azure.tar.gz'
    displayName: Load Docker image
    workingDirectory: $(Build.SourcesDirectory)
    condition: and(succeeded(), eq(variables['RunContainerTests'], 'true'))

  - pwsh: './test/container/RunTests.ps1 -PlanningPokerImageTag "b$env:BUILD_BUILDID" -TestResultPath (Join-Path -Path $env:BUILD_STAGINGDIRECTORY -ChildPath PlanningPokerDocker.TestResult.xml)'
    displayName: 'Run Docker container tests'
    workingDirectory: $(Build.SourcesDirectory)
    condition: and(succeeded(), eq(variables['RunContainerTests'], 'true'))

  - task: PublishTestResults@2
    displayName: Public Docker container test results
    inputs:
      testResultsFormat: NUnit
      searchFolder: $(Build.StagingDirectory)
      testResultsFiles: PlanningPokerDocker.TestResult.xml
      testRunTitle: Planning Poker - Docker
    condition: and(succeededOrFailed(), eq(variables['RunContainerTests'], 'true'))

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: container'
    inputs:
      PathtoPublish: $(Build.SourcesDirectory)/artifacts/staging/planningpoker4azure.tar.gz
      ArtifactName: container
    condition: and(succeeded(), eq(variables['PublishArtifacts'], 'true'))

  - task: CopyFiles@2
    displayName: Copy screenshots
    inputs:
      SourceFolder: $(Build.SourcesDirectory)/artifacts/bin/Duracellko.PlanningPoker.E2ETest/$(BuildConfiguration)/Screenshots
      TargetFolder: $(Build.Build.StagingDirectory)/screenshots
      CleanTargetFolder: true
    condition: and(succeeded(), eq(variables['RunEnd2EndTests'], 'true'))

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: screenshots'
    inputs:
      PathtoPublish: $(Build.Build.StagingDirectory)/screenshots
      ArtifactName: screenshots
    condition: and(succeeded(), eq(variables['RunEnd2EndTests'], 'true'))
